name: OneClickLinks
description: One-time use links for everyone
version: 1.0.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  shelf: any
  shelf_static: any
  shelf_router: ^0.7.2
  mysql1: ^0.17.1
  dotenv: ^2.0.0
  random_string: ^2.0.1

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
  pedantic: ^1.8.0
